export default {
    products: [
        {
            _id: '1',
            name: 'Carrinho de passeio Individual Bebé Confort Soko Shadow Block',
            category: 'Passeio',
            image: '../../public/assets/products/product-1.webp',
            acutalPrice: 167.17 ,
            price: 157.14,
            brand: 'Bebé Confort',
            rating: 4,
            countInStock: 12,
            reviews: 'Such a good price',
        },
        {
            _id: '2',
            name: 'Carrinho de passeio Individual Bebé Confort Soko Shadow Block',
            category: 'Passeio',
            image: '../../public/assets/products/product-1.webp',
            acutalPrice: 167.17 ,
            price: 157.14,
            brand: 'Bebé Confort',
            rating: 4,
            countInStock: 12,
            reviews: 'Such a good price',
        },
        {
            _id: '3',
            name: 'Carrinho de Bebé Individual CONFORT Teeny 3D Blue Chic (Máx. 22 Kg)',
            category: 'Passeio',
            image: '../../public/assets/products/product-2.webp',
            acutalPrice: 167.17 ,
            price: 157.14,
            brand: 'Bebé Confort',
            rating: 4,
            countInStock: 12,
            reviews: 'Such a good price',
        },
        {
            _id: '4',
            name: 'Carrinho de passeio Individual Bebé Confort Soko Shadow Block',
            category: 'Passeio',
            image: '../../public/assets/products/product-3.webp',
            acutalPrice: 167.17 ,
            price: 157.14,
            brand: 'Bebé Confort',
            rating: 4,
            countInStock: 12,
            reviews: 'Such a good price',
        },
        {
            _id: '5',
            name: 'Carrinho de passeio Individual Bebé Confort Soko Shadow Block',
            category: 'Passeio',
            image: '../../public/assets/products/product-4.webp',
            acutalPrice: 167.17 ,
            price: 157.14,
            brand: 'Bebé Confort',
            rating: 4,
            countInStock: 12,
            reviews: 'Such a good price',
        },
          {
            _id: '6',
            name: 'Carrinho de Bebé Individual CONFORT Teeny 3D Blue Chic (Máx. 22 Kg)',
            category: 'Passeio',
            image: '../../public/assets/products/product-2.webp',
            acutalPrice: 167.17 ,
            price: 157.14,
            brand: 'Bebé Confort',
            rating: 4,
            countInStock: 12,
            reviews: 'Such a good price',
        },
        {
            _id: '7',
            name: 'Carrinho de passeio Individual Bebé Confort Soko Shadow Block',
            category: 'Passeio',
            image: '../../public/assets/products/product-3.webp',
            acutalPrice: 167.17 ,
            price: 157.14,
            brand: 'Bebé Confort',
            rating: 4,
            countInStock: 12,
            reviews: 'Such a good price',
        },
        {
            _id: '8',
            name: 'Carrinho de passeio Individual Bebé Confort Soko Shadow Block',
            category: 'Passeio',
            image: '../../public/assets/products/product-4.webp',
            acutalPrice: 167.17 ,
            price: 157.14,
            brand: 'Bebé Confort',
            rating: 4,
            countInStock: 12,
            reviews: 'Such a good price',
        },
      
    ]
}